AllCops:
  TargetRubyVersion: 2.4.1
  Exclude:
    - db/schema.rb
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'spec/**/*'
    - 'lib/tasks/**/*'

  DisplayCopNames: true
  DisplayStyleGuide: true

##################### Style ##################################

Style/AsciiComments:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Lint/RescueException:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty

Style/GuardClause:
  MinBodyLength: 5

Style/Documentation:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: rails

Style/ClassAndModuleChildren:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 7

Style/RedundantSelf:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/FirstParameterIndentation:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

##################### Lint ##################################

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

##################### Metrics ##################################
Metrics/AbcSize:
  Max: 45

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 160
  Exclude:
    - "db/migrate/*.rb"
    - "app/services/ticket_service.rb"

Metrics/MethodLength:
  Max: 30
  Exclude:
    - "db/migrate/*.rb"

Metrics/PerceivedComplexity:
  Max: 8

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - doctor-strange.gemspec

Performance/RedundantMatch:
  Enabled: false
